### ISSUE TITLE
Store hcaptcha cookies 

### ISSUE THREAD

**Issue by AbdullahM0hamed** [ngomile/anigrab#1]
**Is your feature request related to a problem? Please describe.**
I dislike the additional waiting time of having to bypass hcaptcha every single time I download an anime. 

**Describe the solution you'd like**
I'd like to see hcaptcha cookies stored for future use, so that they can be used instead of bypassing the captcha each time. The bypass can then be a fallback in the event that there are no stored cookies or the cookie fails (because of timeout or what-have-you) 

**Describe alternatives you've considered**
There are no alternatives that currently come to mind.

**Comment by ngomile** [comment]
This is something I would like to have solved, I've implemented the caching but finding a good nodejs package to store cookies is a struggle. Even though the token is cached it ends up failing to bypass the captcha probably because cookies aren't being stored. I'll keep looking.

**Comment by ngomile** [comment]
@AbdullahM0hamed try updating to the latest version and trying again. If it works accordingly feel free to close this issue. It still has to do the bypass first but after that the pass token is cached for an hour.

**Comment by AbdullahM0hamed** [comment]
Rip, animepahe went behind cloudflare again
