### ISSUE TITLE
Quality selection 

### ISSUE THREAD

**Issue by TentacleSama4254** [ngomile/anigrab#11]
The downloader works perfectly but I can't seem to slect the quality of the anime for example if I enter - q 720p it logs '720p not found downloading 1080p' even though its actually available. This is for downloads from animeout.xyz btw

**Comment by ngomile** [comment]
Animeout more or less just lists out the episode urls with each url having a separate quality. That's why you should use the filter flag, so instead of anigrab naruto -q 720p it would be anigrab naruto --ft 720p.

**Comment by TentacleSama4254** [comment]
Oh thanks
