### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by TentacleSama4254** [ngomile/anigrab#12]
Error? 
![16091118037741667361372217651502](https://user-images.githubusercontent.com/74726248/103181652-92981980-48c9-11eb-8820-3bf0d1c87e9c.jpg)

**Comment by ngomile** [comment]
May as well just manually delete anigrab's config.json file. It will create it again.

**Comment by TentacleSama4254** [comment]
> May as well just manually delete anigrab's config.json file. It will create it again.

Where is it I can't seem to find

**Comment by TentacleSama4254** [comment]
> May as well just manually delete anigrab's config.json file. It will create it again.

I tired uninstalling and reinstalling the api but same error

**Comment by TentacleSama4254** [comment]
> May as well just manually delete anigrab's config.json file. It will create it again.

![16121326176776611625245903626024](https://user-images.githubusercontent.com/74726248/106400187-fbcbf900-6442-11eb-9b5f-f7fce7ddfbe0.jpg)

**Comment by uali6981** [comment]
> Where is it I can't seem to find

`(Window Drive C, D, E etc):\Users\(Your User Name In Window)\AppData\Roaming\anigrab`
there are two files in this folder delete those files or delete the folder.

I think after this your problem will be solve.
