### ISSUE TITLE
Download Speed slow?

### ISSUE THREAD

**Issue by ajam123** [ngomile/anigrab#17]
Hi, is there any way to increase the download speed?

Downloading using aria2c is slow which is around 500kb/s. Highest is 2MB/s (probably like 10-30seconds till it go slow again).
I tried using IDM, it gives me around 5mb/s download speed.

**Comment by Kgf123** [comment]
Increase the number of connections using -x command.

**Comment by ajam123** [comment]
> Increase the number of connections using -x command.

I increased it to 16 (max amount) but it stayed on 2.
I also changed it on config.json but still same.

**Comment by Kgf123** [comment]
> > Increase the number of connections using -x command.
> 
> I increased it to 16 (max amount) but it stayed on 2.
> I also changed it on config.json but still same.

I have given a pull request woth the changes.  Maybe the owner will merge it later.

**Comment by ajam123** [comment]
fixed by adding options to the aria2c "-k 2M"
