### ISSUE TITLE
[BUG] downloads not working on all sites and Qualities 

### ISSUE THREAD

**Issue by TentacleSama4254** [ngomile/anigrab#22]
I love this npm package but now it won't work, so please look into it :'(

**Comment by ngomile** [comment]
Can you please explain what you mean by it's not working? Each and every source isn't functional? Let me take a look.

**Comment by TentacleSama4254** [comment]
OK I tried again  some sources are working but the main one I'm using doesn't work animeout.xyz
This might be related to them adding the 'checking your browser' thing wen u open the site now

**Comment by TentacleSama4254** [comment]
![1622838491647836559715760542164](https://user-images.githubusercontent.com/74726248/120859208-83687680-c5a1-11eb-8ef1-5008bd46e266.jpg)

But this is basically the output when u enter an animeout.xyz link


![16228385289166398329160965669123](https://user-images.githubusercontent.com/74726248/120859283-9ed38180-c5a1-11eb-83ac-4eeb481e840f.jpg)

**Comment by TentacleSama4254** [comment]
Hope you can do something about it @ngomile

**Comment by ngomile** [comment]
Tried to use the the cf bypass option for requests but that doesn't seem to be going through it. I'm getting a Captcha error, cloudscraper is no longer maintained I believe so might be in need of something else to try to bypass this. But yes animeout is protected now.

**Comment by TentacleSama4254** [comment]
> Tried to use the the cf bypass option for requests but that doesn't seem to be going through it. I'm getting a Captcha error, cloudscraper is no longer maintained I believe so might be in need of something else to try to bypass this. But yes animeout is protected now.

Oh no :(
