### ISSUE TITLE
Bug on download from gogoanime

### ISSUE THREAD

**Issue by rubiin** [ngomile/anigrab#23]
Hello , i am trying to download from gogoanilme using the command 
```
anigrab  beastars -e 1:10 -s gogoanime
```
but its not working

### Expected behavior
Should download

### Actual behavior
Throws resource not found error

### Other details
Additional details and attachments.

**Comment by ngomile** [comment]
I'm failing to reproduce, working as expected. Might be a mistake in the command itself. Try again without the flags, just anigrab beastars -s gogoanime.
