### ISSUE TITLE
having issues using it

### ISSUE THREAD

**Issue by Creator54** [ngomile/anigrab#3]
![share png](https://user-images.githubusercontent.com/34543609/86954684-0e63a580-c174-11ea-9bdf-df8a7692ac48.png)

**Comment by ngomile** [comment]
I've written a fix, please update to the latest version and try again. If it works close the issue and if it doesn't feel free to say so.

**Comment by Creator54** [comment]
> @Creator54 I've written a fix, please update to the latest version and try again. If it works close the issue and if it doesn't feel free to say so.

i did sudo npm update -g anigrab

![share](https://user-images.githubusercontent.com/34543609/86995625-2d3f5780-c1c7-11ea-8e26-ecb6ec7ef5da.png)

**Comment by ngomile** [comment]
@Creator54 I'm failing to reproduce this
![Capture](https://user-images.githubusercontent.com/39145128/87032606-29223280-c1e5-11ea-8e63-dfa4fc03f5d8.PNG)
Have you tried deleting the episode and starting again? It's working fine on my end after the fix, I'm not sure what the problem is now though.

**Comment by Creator54** [comment]
> @Creator54 I'm failing to reproduce this
> ![Capture](https://user-images.githubusercontent.com/39145128/87032606-29223280-c1e5-11ea-8e63-dfa4fc03f5d8.PNG)
> Have you tried deleting the episode and starting again? It's working fine on my end after the fix, I'm not sure what the problem is now though.
yes i even tried in empty dir
now using ryuanime sometimes work sometimes doesnt thnx for this tool though
![share](https://user-images.githubusercontent.com/34543609/87081005-40453c80-c246-11ea-89ba-465c8107200f.png)

**Comment by Creator54** [comment]
works after few tries on ryuanime 
![share png](https://user-images.githubusercontent.com/34543609/87081760-88b12a00-c247-11ea-8375-02c5e4012a4b.png)

**Comment by ngomile** [comment]
@Creator54 I am failing to reproduce the need to execute the command multiple times to start the download as well. It worked immediately, I'm not sure what's up.
![Capture](https://user-images.githubusercontent.com/39145128/87097294-23f4d000-c245-11ea-8cff-c8c272e0cdce.PNG)

**Comment by Creator54** [comment]
ig maybe because u are using cmd & i am on linux terminal
could you check in terminal once ?

**Comment by ngomile** [comment]
@Creator54 I don't have Linux but I just tried to make sure it works on it too at least. So I can't even experiment to see how it will behave. And if you want to switch seasons you just have to do another search for the season you want. If you can't find the season on the site then you try another site.

**Comment by Creator54** [comment]
k thnx nevermind
keep up the open source work

**Comment by Akianonymus** [comment]
@Creator54 I tested on linux and it works fine.
