### ISSUE TITLE
Add a nice error for unsupported websites

### ISSUE THREAD

**Issue by dausruddin** [ngomile/anigrab#6]
**Is your feature request related to a problem? Please describe.**
I was trying bunch of downloader and accidentlaly tried 9anime using this downloader which is not supported. I thought something was broken because it just display
```
Extracting https://www11.9anime.to/watch/gekitou-crush-gear-turbo-dub.57nq/1n27r4q
```
then it terminates. Turned out this downloader doesn't support 9anime.

**Describe the solution you'd like**
Display a nice error when an unknown website is requested.

**Comment by ngomile** [comment]
I'll look into this, it's supposed to behave that way but I think there's a slight flaw in the logic.

**Comment by ngomile** [comment]
This has been fixed since a while ago, closing.
